checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - test/*
        - vendor/*

build:
    environment:
        php:
            version: 7.2

before_commands:
  - composer install --prefer-source
